language: java

sudo: enable
dist: trusty

jdk:
 - oraclejdk8

addons:
    sonarcloud:
     organization: "helenfranca-github"
     token:
      secure: $sonnar_key
      
script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

branches:
  only:
    - master
    - devHelen

notifications:
    slack: bsi-ifserra:TYWamFXEYGbYjKP2ZwLUZECP
