language: java

sudo: enable
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
    - master
    - devHelen
   
before_script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
  -mvn sonar:sonar
  -Dsonar.organization=malufreitas-github
  -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=8d045809ae63a604ff4a08821cf2fc190bed19fa

  
 notifications:
    slack: bsi-ifserra:TYWamFXEYGbYjKP2ZwLUZECP
    
