language: java

jdk:
 - oraclejdk8 

branches:
  only
    - master
   
before:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
  
 notifications:
    slack: bsi-ifserra:TYWamFXEYGbYjKP2ZwLUZECP
    
