language: java

jdk:
 - oraclejdk8
 
sudo: enable
dist: trusty

addons:
    sonarcloud:
    organization: "helenfranca-github"
    token:
      secure: $sonnar_key

branches:
  only:
    - master
    - devHelen
   
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
 notifications:
    slack: bsi-ifserra:TYWamFXEYGbYjKP2ZwLUZECP
    
