language: java

jdk:
 - oraclejdk8 

branches:
  only
    - master
   
before:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
- mvn sonar:sonar \
  -Dsonar.organization=malufreitas-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=8d045809ae63a604ff4a08821cf2fc190bed19fa

  
 notifications:
    slack: bsi-ifserra:TYWamFXEYGbYjKP2ZwLUZECP
    
